### ISSUE TITLE
Disciplines: "Alltagskultur, Ernährung, Soziales (AES)"

### ISSUE THREAD

**Issue by Criamos** [openeduhub/oeh-metadata-vocabs#13]
Bei den Arbeiten am Crawler für DiLerTube kam mir das Fach "AES" zum ersten Mal unter:
https://www.dilertube.de/alltagskultur-ernaehrung-soziales-aes.html

Scheint wohl 2016 in BaWü eingeführt worden zu sein → Realschule ab Klasse 7?
https://www.lmz-bw.de/medien-und-bildung/weiterfuehrende-schulen/bildungsplan-2016-sekundarstufe-i/alltagskultur-ernaehrung-soziales/

Im Crawler würde ich es noch am ehesten auf "Ernährung und Hauswirtschaft" mappen, aber eine genauere Zuordnung, die alle Bereiche des Fachs umfasst, fällt schwer. Wo könnte das Fach als `altLabel` am besten verortet werden?

**Comment by sroertgen** [comment]
@Criamos Habe ich als neues Fach hinzugefügt, weil es sonst m.E. nirgends gut gepasst hat
