### ISSUE TITLE
Mechatronik als Schulfach hinzufügen

### ISSUE THREAD

**Issue by sroertgen** [openeduhub/oeh-metadata-vocabs#2]
@Criamos Wo kam nochmal der Bedarf nach Mechatronik her?

**Comment by Criamos** [comment]
@sroertgen Aus dem Zentralabitur Niedersachsen (`niedersachsen_abi_spider`) u.a. im Jahrgang 2021 zu finden

**Comment by sroertgen** [comment]
@Criamos finally done.
