### ISSUE TITLE
Disciplines-Mapping: "Arbeit, Wirtschaft, Technik" & "Verbraucherbildung"

### ISSUE THREAD

**Issue by Criamos** [openeduhub/oeh-metadata-vocabs#3]
- [x] **"Arbeit, Wirtschaft, Technik"** (anscheinend oft als AWT oder WAT (je nach Bundesland) abgekürzt) entspricht wohl der [Arbeitslehre](https://de.wikipedia.org/wiki/Arbeitslehre). 
Hier stellt sich zudem die Frage, ob "Polytechnischer Unterricht" oder "Polytechnik" hier auch zu mappen wäre (wenn das überhaupt noch irgendwo in den Lehrplänen auftaucht als Begriff?)
- [x] **"Verbraucherbildung"** ist u.a. in Schleswig-Holstein wohl [der neue Begriff](https://lehrplan.lernnetz.de/?wahl=149) für "Haushaltslehre", aber wohl nicht bundesweit ein eigenes Schulfach. In welchen Bundesländern das Teil des Lehrplans ist, [listet die Verbraucherzentrale hier auf](https://www.verbraucherbildung.de/verbraucherbildung-fuer-schulen).
- optional, je nachdem ob es Sinn macht oder nicht: "Fächerübergreifend" wird bei Umwelt-im-Unterricht.de [als Schulfach-Filter genutzt](https://www.umwelt-im-unterricht.de/suche/?tx_solr%5Bfilter%5D%5B0%5D=subject%3AF%C3%A4cher%C3%BCbergreifend).

**Comment by sroertgen** [comment]
Punkte 1 und 2 sind erledigt.

Bei "Fächerübergreifend" zögere ich etwas, da wir einerseits bereits "Allgemein" haben, das alle Fächer betreffende Materialien kennzeichnen kann.
Außerdem denke ich, das bestimmte fächerübegreifende Materialien dann so klassifiziert werden, dass die entsprechenden Fächer alle angewählt werden. 
Bsp: Wenn mein Material die Fächer Deutsch, Mathematik und Biologie abdeckt, würde ich diese Fächer auswählen und nicht einfach "fächerübergreifend". So lassen sich dann auch in der Suche durch das Auswählen dieser Fächer die entsprechenden Materialien wieder finden. 

Was meinst du @torsten-simon ?
