### ISSUE TITLE
`discipline`-Vocab: eafCodes (Esperanto / Mechatronik / Körperpflege)

### ISSUE THREAD

**Issue by Criamos** [openeduhub/oeh-metadata-vocabs#35]
Beim Vergleich unserer `discipline.ttl` ([Link](https://github.com/openeduhub/oeh-metadata-vocabs/blob/master/discipline.ttl)) mit der EAF Sachgebietssystematik [eafsys.txt](http://agmud.de/wp-content/uploads/2021/09/eafsys.txt) der AGMuD fielen mir Probleme auf:

### Problem 1: `Esperanto`
- `Esperanto` trägt im `discipline`-Vocab (siehe [Zeile 139](https://github.com/openeduhub/oeh-metadata-vocabs/blob/master/discipline.ttl#L139)) den Key `20090`
- laut `eafsys.txt` wäre der korrekte Eintrag jedoch unter `20080      # Esperanto` verortet

**Lösungsvorschlag:** 
Eintrag auf `20080` ändern.

### Problem 2: Mechatronik
- Das `discipline`-Vocab für `Mechatronik` ist unter dem (custom) Key `<oeh04010>` zu finden
    - wahrscheinlich dadurch bedingt, dass der `discipline`-Eintrag `04010` dem prefLabel "Körperpflege" zugeordnet wurde (siehe [Z.227](https://github.com/openeduhub/oeh-metadata-vocabs/blob/master/discipline.ttl#L227))
- in der `eafsys.txt` existiert das Äquivalent zum Eintrag unter `04010      # Fahrzeugtechnik, Mechatronik`

Lösungsvorschlag:
Zuerst Problem 2.1 beseitigen, dann `Mechatronik` auf `04010` verschieben.

#### Problem 2.1: Eintrag `Körperpflege` von `04010` auf `2600103` umziehen
- in der `eafsys.txt` gibt es  zwei Einträge für das Sachgebiet "Körperpflege":
    - `2600103    #  Körperpflege` (Im Unterbaum von "Gesundheit")
    - `0401804    #  Körperpflege` (Im Unterbaum von "Dienstleistung")

**Lösungsvorschlag:**
"Körperpflege" zukünftig unter `2600103` verorten.

**Comment by lummerland** [comment]
The fix is not urgent but no big deal as well, so I just made it.
