### ISSUE TITLE
fskRating Vocab - altLabels (for YouTube)

### ISSUE THREAD

**Issue by Criamos** [openeduhub/oeh-metadata-vocabs#9]
# Problem 1 - altLabels:
YouTube's Data API v3 has a field for [fskRating](https://developers.google.com/youtube/v3/docs/videos#contentDetails.contentRating.fskRating) with the following list of valid values:

> **Valid values for this property are:**
> **fsk0** – FSK 0
> **fsk12** – FSK 12
> **fsk16** – FSK 16
> **fsk18** – FSK 18
> **fsk6** – FSK 6
> **fskUnrated**

Currently, the [fskRating-Vocabulary](https://github.com/openeduhub/oeh-metadata-vocabs/blob/master/fskRating.ttl) has `prefLabel`s from "0" to "18" for these FSK ratings.

# Proposal:
Add `altLabel`s to the vocab so we don't have to map fskRatings, e.g.: `prefLabel` "0" comes with the `altLabel` "fsk0"

# Problem 2 - fskUnrated:
YouTube's API allows the value "fskUnrated" - how should this value be treated? (Is a vocab value necessary for this edge-case?)

**Comment by sroertgen** [comment]
@Criamos added altLabels as suggested.

regarding Problem 2: We should not index content that is unrated I guess. If this affects a lot of sources, we should talk about this in the next conference.
